// <auto-generated />
using System;
using Loop.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loop.Infra.Data.Migrations
{
    [DbContext(typeof(LoopDbContext))]
    partial class LoopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Loop.Domain.Entities.Frequencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<int>("EstagiarioId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HoraChegada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraSaida")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HorasTrabalhadas")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EstagiarioId");

                    b.ToTable("Frequencias", (string)null);
                });

            modelBuilder.Entity("Loop.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Loop.Domain.Entities.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstagiarioId")
                        .HasColumnType("int");

                    b.Property<int>("FrequenciaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HorarioEntrada")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HorarioSaida")
                        .HasColumnType("time(6)");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RespostaData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RespostaGestor")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstagiarioId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("Loop.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("Loop.Domain.Entities.Perfil");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Loop.Domain.Entities.Estagiario", b =>
                {
                    b.HasBaseType("Loop.Domain.Entities.Perfil");

                    b.ToTable("Estagiarios", (string)null);
                });

            modelBuilder.Entity("Loop.Domain.Entities.Gestor", b =>
                {
                    b.HasBaseType("Loop.Domain.Entities.Perfil");

                    b.ToTable("Gestores", (string)null);
                });

            modelBuilder.Entity("Loop.Domain.Entities.Frequencia", b =>
                {
                    b.HasOne("Loop.Domain.Entities.Estagiario", "Estagiario")
                        .WithMany("Frequencias")
                        .HasForeignKey("EstagiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estagiario");
                });

            modelBuilder.Entity("Loop.Domain.Entities.Solicitacao", b =>
                {
                    b.HasOne("Loop.Domain.Entities.Estagiario", null)
                        .WithMany("Solicitacoes")
                        .HasForeignKey("EstagiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loop.Domain.Entities.Estagiario", b =>
                {
                    b.Navigation("Frequencias");

                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
