# Acesse https://aka.ms/customizecontainer para saber como personalizar seu contêiner de depuração e como o Visual Studio usa este Dockerfile para criar suas imagens para uma depuração mais rápida.

# Esta fase é usada durante a execução no VS no modo rápido (Padrão para a configuração de Depuração)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# Esta fase é usada para compilar o projeto de serviço
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Loop.API.MVC/Loop.API.MVC.csproj", "Loop.API.MVC/"]
COPY ["Loop.Application/Loop.Application.csproj", "Loop.Application/"]
COPY ["Loop.Domain/Loop.Domain.csproj", "Loop.Domain/"]
COPY ["Loop.Infra.Data/Loop.Infra.Data.csproj", "Loop.Infra.Data/"]
COPY ["Loop.Infra.IoC/Loop.Infra.IoC.csproj", "Loop.Infra.IoC/"]
RUN dotnet restore "./Loop.API.MVC/Loop.API.MVC.csproj"
COPY . .
WORKDIR "/src/Loop.API.MVC"
RUN dotnet build "./Loop.API.MVC.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Esta fase é usada para publicar o projeto de serviço a ser copiado para a fase final
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Loop.API.MVC.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Esta fase é usada na produção ou quando executada no VS no modo normal (padrão quando não está usando a configuração de Depuração)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Loop.API.MVC.dll"]