// <auto-generated />
using System;
using Loop.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loop.Infra.Data.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260130172826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Loop.Domain.Entities.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Loop.Domain.Entities.Estagiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Estagiarios");
                });

            modelBuilder.Entity("Loop.Domain.Entities.Gestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("Loop.Domain.Requests.Frequencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstagiarioId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HoraChegada")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraSaida")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HorasTrabalhadas")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("EstagiarioId");

                    b.ToTable("Frequencias");
                });

            modelBuilder.Entity("Loop.Domain.Requests.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstagiarioId")
                        .HasColumnType("int");

                    b.Property<int>("FrequenciaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HorarioEntrada")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HorarioSaida")
                        .HasColumnType("time(6)");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RespostaData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RespostaGestor")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstagiarioId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("Loop.Domain.Requests.Frequencia", b =>
                {
                    b.HasOne("Loop.Domain.Entities.Estagiario", "estagiario")
                        .WithMany("frequencias")
                        .HasForeignKey("EstagiarioId");

                    b.Navigation("estagiario");
                });

            modelBuilder.Entity("Loop.Domain.Requests.Solicitacao", b =>
                {
                    b.HasOne("Loop.Domain.Entities.Estagiario", null)
                        .WithMany("solicitacoes")
                        .HasForeignKey("EstagiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Loop.Domain.Entities.Estagiario", b =>
                {
                    b.Navigation("frequencias");

                    b.Navigation("solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
